on:
  workflow_dispatch:
    inputs:
      versionToTest:
        description: 'Version of dl4j to test'
        required: false
        default: 1.0.0-SNAPSHOT


      backendToTest:
        description: "The artifactId of the nd4j backend to test"
        required: false
        default: nd4j-native

      testHeapSize:
          description: "The java heap size to run tests at"
          required: false
          default: 4g

      testOffHeapSize:
        description: "The off heap size to run tests at"
        required: false
        default: 4g

      testTags:
        description: "The tags of the tests to run"
        required: false
        default: samediff,rng,java-only,dl4j-old-api,ndarray-indexing,compression,loss-functions,keras,python,tensorflow,onnx

      testExcludeTags:
        description: "The tags of the tests to exclude"
        required: false
        default: large-resources,downloads,long-running-test

      javacppNoPointerGc:
        description: "Whether to turn off pointer gc in javacpp"
        required: false
        default: true

      surefireForks:
        description: "Number of java processes to run for tests"
        required: false
        default: 1

      surefireThreads:
        description: "Number of threads to use for each fork for tests"
        required: false
        default: 1

jobs:
  #Note: no -pl here because we publish everything from this branch and use this as the basis for all uploads.
  linux-x86_64:
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run cpu tests
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            cd ${GITHUB_WORKSPACE}/platform-tests && mvn -Dsurefire.forks=${{ github.event.inputs.surefireForks }} -Dsurefire.threads=${{ github.event.inputs.surefireThreads }} -Dbackend.artifactId=${{ github.event.inputs.backendToTest }} -DexcludedTests=${{ github.event.inputs.testExcludeTags }}  -Dtests=${{ github.event.inputs.testTags }} -Dtest.nogc=${{ github.event.inputs.javacppNoPointerGc }} -Dtest.offheap.size=${{ github.event.inputs.testOffHeapSize }} -Dtest.heap.size=${{ github.event.inputs.testHeapSize }} -Ddl4j.version=${{ github.event.inputs.versionToTest }}  -Djavacpp.platform=linux-x86_64 clean test


